timezone: America/Los_Angeles
env: PRODUCTION
developer: Brightside Tech
developerUrl: "https://godiego.me"
url: https://www.bgcofcv.org
markdown: kramdown
destination: dist
source: root/jekyll
include:
  - _pages
  - admin
exclude:
  - dev_admin
plugins:
  - jemoji
  - jekyll-sitemap
future: true
collections:
  our-clubs:
    output: true
  program-categories:
    output: true
  events:
    output: true
  campaigns:
    output: false
